spring:
  application:
    name: fenix-flash
  datasource:
    name: flash
    generate-unique-name: false
    url: jdbc:h2:mem:flash
    username: root
    password: root
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 dia em milissegundos
