spring:
  application:
    name: fenix-flash
  datasource:
    name: flash
    url: jdbc:postgresql://localhost:5432/flash
    username: hangalo
    password: c0mpl3xpb@369
    driver-class-name: org.postgresql.Driver


  servlet:
    multipart:
      max-file-size: 5MB

  jpa:
    hibernate:
      ddl-auto: update

file:
  upload:
    dir: ./uploads

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 dia
